buildall: question1 question2 question3

question1.o: collatz.c
	gcc -c -o collatz.o collatz.c

question2.o: question2.c
	gcc question2.c -o question2 

question3.o: checksum.c
	gcc checksum.c -o checksum


runall:



clean:
	rm *.o *.gv